### ISSUE TITLE
Lombok Dependency Issue.

### ISSUE THREAD

**Issue by Vinayrraj** [amigoscode/spring-boot-fullstack-professional#15]
This is was a version issue, 

To resolve that, use below version win the pom.xml:

<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>1.18.24</version>
	<optional>true</optional>
</dependency>

**Comment by Vinayrraj** [comment]
`<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>1.18.24</version>
	<optional>true</optional>
</dependency>`

**Comment by chapman-cc** [comment]
@amigoscode please add this to the read me or the pom file
I was watching your video and spend some time looking for this problem
